# fly.toml — SEU Scheduler (Flask + SQLite)

app = "seu-scheduler"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  DB_PATH = "/data/app.db"

[[mounts]]
  source = "vol_rn8ymk3xjz3w918r"          # ← الاسم الصحيح للـVolume
  destination = "/data"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.checks]
    [services.checks.http_check]
      path = "/healthz"
      interval = "10s"
      timeout = "2s"
