app = "seu-scheduler"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "off"
  min_machines_running = 1
  
# احذف كتلة [[http_service.checks]] كاملة مؤقتًا

[[mounts]]
  source = "data"
  destination = "/data"
