app = "seu-scheduler"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  auto_start_machines = true
  auto_stop_machines = "off"
  min_machines_running = 1
